### ISSUE TITLE
Microsoft.Dynamics.Integration.AAL+Common references

### ISSUE THREAD

**Issue by iambigred** [Microsoft/Instance-Adapter-for-Microsoft-Dynamics-CRM#1]
I've downloaded the solution from [here](http://microsoft.github.io/Instance-Adapter-for-Microsoft-Dynamics-CRM/) Where can I find these missing assembly references?
- Microsoft.Dynamics.Integration.AAL
- Microsoft.Dynamics.Integration.Common

![Missing references](http://i.imgur.com/bUS3NbD.png)

**Comment by thehetz** [comment]
They are included with the Connector for Microsoft Dynamics install.  Once you have installed Connector, the references should auto-resolve.  If they don't you can find them in C:Program Files(x86)\Microsoft Dynamics\Microsoft Dynamics Adapter\
